# Generated by Django 4.2.29 on 2026-04-04 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice')], max_length=50)),
                ('required', models.BooleanField(default=True)),
                ('display_mode', models.CharField(blank=True, choices=[('default', 'Default'), ('checkbox', 'Checkbox'), ('multi_select', 'Multi Select')], default='default', max_length=50)),
                ('option_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questionnaires.optiongroup')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaires.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('option_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questionnaires.optiongroup')),
            ],
        ),
    ]
