# Generated by Django 4.2.29 on 2026-04-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_alter_question_options_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceoption',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
