# Generated by Django 4.2.29 on 2026-04-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0004_choiceoption_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceoption',
            name='is_permanent',
            field=models.BooleanField(default=False),
        ),
    ]
