# Generated by Django 4.2.29 on 2026-04-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_response_respondent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='respondent_name',
        ),
    ]
