# Generated by Django 4.2.29 on 2026-04-13 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0004_choiceoption_department'),
        ('responses', '0003_remove_response_respondent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='response',
            name='respondent_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.question'),
        ),
    ]
